version: "3.7"
services:
  run:
    build: .
    volumes: 
      - ./code:/code
    command: sh -c "python agent.py"
    cap_drop: 
      - ALL
    network_mode: "none"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 250M